import NavBar from './navbar';
import { Footer } from './footer';
import Head from 'next/head';
import BackgroundAnimation from '../background';

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Testng</title>
        <meta name="viewport" contet="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen">
        <div className="flex flex-col h-full">
          {/*<NavBar />*/}
          {children}
          <div className="absolute -z-10 w-screen h-screen top-0 left-0">
            <BackgroundAnimation />
          </div>
        </div>
      </div>
    </>
  );
}

export default Layout;
